name: "CI to Pull Requested"
on: 
  repository_dispatch:
    type: [run-tests]
    
jobs:
  running-e2e-tests:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL_REGISTER: ${{ secrets.USER_EMAIL_REGISTER }}
      USER_LOGIN: ${{ secrets.USER_EMAIL_REGISTER }}
      USER_PASSWORD: ${{ secrets.USER_EMAIL_REGISTER }}
      USER_NAME: ${{ secrets.USER_EMAIL_REGISTER }}
      PGP_URL: ${{ secrets.USER_EMAIL_REGISTER }}
      PGP_URL_ADMIN: ${{ secrets.USER_EMAIL_REGISTER }}
      BASE_UI_URL: ${{ secrets.USER_EMAIL_REGISTER }}
      BASE_URL: 'https://c29de7f7a5595b.lhr.life'
    steps:
      - name: 'health cheack tunnel'
        continue-on-error: true
        run: |
          curl -X GET \
              -H "Accept: application/json" \
              -H "bypass-tunnel-reminder: 123" \
              https://c29de7f7a5595b.lhr.life \'
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - run: npm i
      - run: npm run test:api
